source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/elegion/ios-podspecs.git'

target 'elnutils', :exclusive => true do
    pod 'ELNUtils', :path => '../'
end

target 'elnutilsTests', :exclusive => true do
    pod 'ELNUtils', :path => '../'
end
